### ISSUE TITLE
Benchmark plugin fails to build on Swift 6.1

### ISSUE THREAD

**Issue by glbrntt** [ordo-one/benchmark#369]
`swift package benchmark` fails to build with Swift 6.1 since v1.36.1:

```
$ swift package benchmark
[10/10] Linking BenchmarkBoilerplateGenerator-toolerror: build planning stopped due to build-tool plugin failures
```

The verbose output shows a little more:

```
$ swift package --verbose benchmark
/Users/georgebarnett/workspace/github.com/apple/swift-nio/Benchmarks/.build/checkouts/package-benchmark/Plugins/BenchmarkPlugin/BenchmarkSupportPlugin.swift:21:22: error: 'directoryURL' is unavailable
19 |         // starting with the 6.x tools-version; older toolchains only have `Path`.
20 |         #if compiler(>=6.1)       
21 |         guard target.directoryURL.deletingLastPathComponent().lastPathComponent == "Benchmarks" else { return [] }
   |                      `- error: 'directoryURL' is unavailable                                                                            
22 | 
23 |         let swiftFile = context.pluginWorkDirectoryURL.appending(path: "__BenchmarkBoilerplate.swift")

PackagePlugin.SwiftSourceModuleTarget.directoryURL:3:14: note: 'directoryURL' was introduced in PackageDescription 6.0                                                                                                                                                                    
1 | struct SwiftSourceModuleTarget {
2 | @available(_PackageDescription 6.0)
3 |   public let directoryURL: URL}               
  |              `- note: 'directoryURL' was introduced in PackageDescription 6.0                                                                                                                                                                                                         
4 |                                                             
                                                                      
/Users/georgebarnett/workspace/github.com/apple/swift-nio/Benchmarks/.build/checkouts/package-benchmark/Plugins/BenchmarkPlugin/BenchmarkSupportPlugin.swift:23:33: error: 'pluginWorkDirectoryURL' is unavailable
21 |         guard target.directoryURL.deletingLastPathComponent().lastPathComponent == "Benchmarks" else { return [] }                                                                                                                                                                   
22 |              
23 |         let swiftFile = context.pluginWorkDirectoryURL.appending(path: "__BenchmarkBoilerplate.swift")
   |                                 `- error: 'pluginWorkDirectoryURL' is unavailable                                                                                                                                                                                                    
24 |         let inputFiles = target.sourceFiles.filter { $0.url.pathExtension == "swift" }.map(\.url)                                                                                                                                                                                    
25 |         let outputFiles: [URL] = [swiftFile]

(etc. etc.)
```

**Comment by supersonicbyte** [comment]
Sorry for the inconvenience! Should be fixed with: https://github.com/ordo-one/benchmark/pull/370

**Comment by glbrntt** [comment]
Thanks!
